execute pathogen#infect()

set secure
set exrc
set nowrap
set hidden
set expandtab
set smarttab
set tabstop=4
set shiftwidth=4
colorscheme lucius
syntax on
set pastetoggle=<F2>
set fileformat=unix
set backspace=indent,eol,start
set autoindent
set cindent
set foldmethod=syntax
set number
if &term =~ "xterm"
 set t_Co=256
 if has("terminfo")
   let &t_Sf=nr2char(27).'[3%p1%dm'
   let &t_Sb=nr2char(27).'[4%p1%dm'
 else
   let &t_Sf=nr2char(27).'[3%dm'
   let &t_Sb=nr2char(27).'[4%dm'
 endif
endif

let NERDTreeDirArrowExpandable = "▶"
let NERDTreeDirArrowCollapsible = "▼"

scriptencoding utf-8
set encoding=utf-8

let g:webdevicons_enable_nerdtree = 1
let g:WebDevIconsUnicodeDecorateFolderNodes = 1
let g:webdevicons_enable_airline_statusline = 1
let g:DevIconsEnableFoldersOpenClose = 1
let g:DevIconsEnableFolderExtensionPatternMatching = 0

let g:syntastic_cpp_compiler_options = ' -std=c++11'
let g:syntastic_cpp_check_header = 1
let g:syntastic_cpp_auto_refresh_includes = 1

let g:syntastic_c_check_header = 1
let g:syntastic_c_auto_refresh_includes = 1

let g:syntastic_java_javac_delete_output = 0
let g:syntastic_java_javac_autoload_maven_classpath = 1

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

let g:syntastic_python_python_exec = 'python3'

let g:EasyMotion_do_mapping = 0
nmap s <Plug>(easymotion-s)
nmap s <Plug>(easymotion-s2)
let g:EasyMotion_smartcase = 1

let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamemod = ':t'
let g:airline_powerline_fonts = 1

let g:nerdtree_tabs_open_on_console_startup = 1
let g:NERDTreeWinSize=30

autocmd VimEnter * if &modifiable | NERDTreeFind | wincmd p | endif

autocmd WinEnter * call s:CloseIfOnlyNerdTreeLeft()

" Close all open buffers on entering a window if the only
" buffer that's left is the NERDTree buffer
function! s:CloseIfOnlyNerdTreeLeft()
  if exists("t:NERDTreeBufName")
    if bufwinnr(t:NERDTreeBufName) != -1
      if winnr("$") == 1
        q
      endif
    endif
  endif
endfunction

let g:syntastic_cpp_config_file = '.syntastic_cpp_config'
