execute pathogen#infect()

set nowrap
set hidden
set smarttab
set tabstop=4
set shiftwidth=4
colorscheme lucius
syntax on
set pastetoggle=<F2>
set fileformat=unix
set backspace=indent,eol,start
set autoindent
set cindent
set foldmethod=syntax
if &term =~ "xterm"
 set t_Co=256
 if has("terminfo")
   let &t_Sf=nr2char(27).'[3%p1%dm'
   let &t_Sb=nr2char(27).'[4%p1%dm'
 else
   let &t_Sf=nr2char(27).'[3%dm'
   let &t_Sb=nr2char(27).'[4%dm'
 endif
endif

set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_java_javac_autoload_maven_classpath = 1
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

let g:nerdtree_tabs_open_on_console_startup = 1

let g:EasyMotion_do_mapping = 0
nmap s <Plug>(easymotion-s)
nmap s <Plug>(easymotion-s2)
let g:EasyMotion_smartcase = 1

let g:NERDTreeWinSize=40

autocmd VimEnter * if &modifiable | NERDTreeFind | wincmd p | endif
